batt = Battery('Name', 'Battery',...
    'N_p', compParam('N_p',1,'AutoRename', true, 'Tunable', true),...
    'N_s', compParam('N_s',3, 'AutoRename', true, 'Tunable', true)); % 4000mAh, 3S Default Battery, No Dynamics
prop = Propeller('Name', 'Propeller',...
    'k_P', compParam('k_P', 0.03, 'AutoRename', true, 'Tunable', true),...
    'k_T', compParam('k_T', 0.05, 'AutoRename', true, 'Tunable', true),...
    'D', compParam('D', 0.1270, 'AutoRename', true, 'Tunable', true),...
    'M', extrinsicProp('Mass', 0.008, 'AutoRename',true,'Tunable',true),...
    'J', compParam('J', 2.1075e-05, 'AutoRename', true, 'Tunable',true));
motor = PMSMMotor('Name','Motor',...
    'M', extrinsicProp('Mass',0.04, 'AutoRename', true, 'Tunable', true),...
    'J', compParam('J', 6.5e-6, 'AutoRename', true, 'Tunable', true),...
    'K_t', compParam('K_t', 0.00255, 'AutoRename', true, 'Tunable', true),...
    'Rm', compParam('Rm',0.117, 'AutoRename', true, 'Tunable', true));
%%
sqr = QuadRotor('Battery', batt, 'Propeller', prop, 'PMSMMotor', motor);